spring:
    datasource:
        url: jdbc:postgresql:mydb
        username: user01
        password: password
    jpa:
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE